//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eleks.WindowsAzure.Tools.AzureSqlDbBlobBackup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eleks.WindowsAzure.Tools.AzureSqlDbBlobBackup.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ExportInput xmlns=&quot;http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.ServiceTypes&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;BlobCredentials i:type=&quot;BlobStorageAccessKeyCredentials&quot;&gt;
        ///    &lt;Uri&gt;{0}&lt;/Uri&gt;
        ///    &lt;StorageAccessKey&gt;{1}&lt;/StorageAccessKey&gt;
        ///  &lt;/BlobCredentials&gt;
        ///  &lt;ConnectionInfo&gt;
        ///    &lt;DatabaseName&gt;{2}&lt;/DatabaseName&gt;
        ///    &lt;Password&gt;{3}&lt;/Password&gt;
        ///    &lt;ServerName&gt;{4}&lt;/ServerName&gt;
        ///    &lt;UserName&gt;{5}&lt;/UserName&gt;
        ///  &lt;/ConnectionInfo&gt;
        ///&lt;/ExportInput&gt;.
        /// </summary>
        internal static string BackupRequestTemplate {
            get {
                return ResourceManager.GetString("BackupRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:
        ///
        ///  AzureSqlDbBlobBackup.exe
        ///    --dac-service-url=&quot;http://by1prod-dacsvc.azure.com/DACWebService.svc&quot;
        ///    --db-server-name=&quot;abcdef1234.database.windows.net&quot;
        ///    --db-name=&quot;Northwind&quot;
        ///    --db-username=&quot;db-admin&quot;
        ///    --db-password=&quot;db-admin-secret&quot;
        ///    --blob-container=&quot;https://myaccount.blob.core.windows.net/backups&quot;
        ///    --storage-account-key=&quot;xSS7u0VAooryYw==&quot;
        ///
        ///DACWebService URLs (as of October 2012):
        ///
        ///  North Central US : http://ch1prod-dacsvc.azure.com/DACWebService.svc
        ///  South Cen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpPostOptionsText {
            get {
                return ResourceManager.GetString("HelpPostOptionsText", resourceCulture);
            }
        }
    }
}
